### ISSUE TITLE
Arquivo ausente

### ISSUE THREAD

**Issue by zanderaugusto** [brunobrr/bdc#106]
A leitura do seguinte arquivo não ocorre:

https://github.com/brunobrr/bdc/blob/523fa9518f7e332d46f13cc88c366925770fe908/vignettes/01_coordinate_corrections.R#L41

Tentei encontrar em qual script e linha se salvava um arquivo **.xz**, mas não encontrei menção alguma. Há apenas arquivos **.qs** no primeiro [script](vignettes/00_Merge_Datasets.R). 

Ademais, corrigir #105, uma vez que está em conflito com este script, no que consta à ordem.

**Comment by brunobrr** [comment]
@zanderaugusto, 

Esse arquivo é antigo e será apagado. Pode pular para o script 02_Prefilter.
Valeu pela força!!!

**Comment by brunobrr** [comment]
@zanderaugusto,

Esse arquivo é antigo e será apagado. Pode pular para o script 02_Prefilter.
Valeu pela força!!!
