### ISSUE TITLE
'Check_5' em '01_Prefilter'

### ISSUE THREAD

**Issue by zanderaugusto** [brunobrr/bdc#109]
https://github.com/brunobrr/bdc/blob/547c4926eb669c504eb767f1c3b299c6eee0dfa2/vignettes/01_Prefilter.R#L69

Erro:

>  Error in countrycode::countrycode(cntr_db$cntr_suggested, origin = "country.name.en",:  sourcevar must be a character or numeric vector. This error often arises when users pass a tibble (e.g., from dplyr) instead of a column vector from a data.frame (i.e., my_tbl[, 2] vs. my_df[, 2] vs. my_tbl[[2]])

Erro remete especificamente à função:

https://github.com/brunobrr/bdc/blob/547c4926eb669c504eb767f1c3b299c6eee0dfa2/R/bdc_standardize_country.R#L88

Input e bases de dados utilizados disponíveis em:

https://github.com/zanderaugusto/bdc/tree/master/Config

**Comment by brunobrr** [comment]
@sjevelazco, você pode conferir isso, por favor? Acho que é coisa rápida.
Acredito que seja algum problema de indexação (ou então de usar ou não aspas no dplyr).

**Comment by brunobrr** [comment]
@zanderaugusto, acho que o problema foi resolvido. Quando testar me dá um retorno, por favor?
