### ISSUE TITLE
Documentação funções

### ISSUE THREAD

**Issue by brunobrr** [brunobrr/bdc#125]
Exemplo de documentação para pronização das funções (sugestões? sempre bem-vindas!). Veja exemplo em **bdc_flag_missing_names.R**

```
#' Título: sem pontos final [Nome título não é necessário]
#' Descrição: com ponto final. [Nome descrição não é necessário]
#'
#' Campos: [argumento][tipo.] [Descrição...] [Default = "", sem houver] [Ponto final]  
#' @param data data.frame. Containing... [Ponto final]
#' @param sci_names character string.  The column with ... Default = "nome" [Ponto final].
#' @param lat numeric. The column with ... Default = "nome" [Ponto final].
#' @param lon numeric. The column with ... Default = "nome" [Ponto final].
#'
#' @details This test flags....[Ponto final]
#' @return A data. frame with...
#' @examples
#' \dontrun{
#' x <- data.frame(scientificName = c("Ocotea odorifera", NA, "Panthera onca", ""))
#' bdc_flag_missing_names(x)
#' }

```

A divisão para revisar as funções ficou da seguinte maneira:
**Karlo**
- [x] bdc_standardize_datasets
- [x] bdc_creates_dir
- [x] bdc_missing_xy
- [x] bdc_missing_names
- [x] bdc_invalid_xy
- [x] bdc_invald_basis_of_records
- [x] bdc_xy_out_country (não encontrada)
- [x] bdc_country_xy_mismatch
**Santiago**
- [x] bdc_transposed_xy
- [x] bdc_get_wiki_country
- [x] bdc_standardize_country
- [x] bdc_correct_coordinates
- [x] bdc_coord_trans
- [x] bdc_xy_precision
**Geizi**
- [x] bdc_summary_col
- [x] bdc_create_report
- [x] bdc_xy_from_locality
- [x] bdc_create_figures
- [x] bdc_filter_out_flags (melhorar o exemplo da função)
- [x] bdc_query_names_taxadb
**Lucas**
- [x] bdc_query_names_taxadb
- [x] bdc_filter_out_names
- [x] bdc_clean_names
- [x] bdc_suggest_names_taxadb
- [x] bdc_clean_duplicates
- [x] bdc_parse_date

**Comment by kguidonimartins** [comment]
Pessoal, lembrem de um detalhe importante sobre os `@examples`: o código precisar ficar dentro de um `\dontrun{}`. Vejam abaixo:

```
#' @examples
#' \dontrun{
#' x <- data.frame(scientificName = c("Ocotea odorifera", NA, "Panthera onca", ""))
#' bdc_flag_missing_names(x)
#' }
```

Isso evita que o processo de checagem dos metadados do pacote e o de criação automática da documentação testem esses exemplos. Fiz algumas checagens hoje e esse detalhe tem retornado *warnings* e *errors*.

**Comment by brunobrr** [comment]
@kguidonimartins, devemos adicionar o @param importFrom em todas as funções?
Você pode atualizar a documentação das funções, por favor? Estou curiosa para ver como esta ficando, rs

**Comment by kguidonimartins** [comment]
Sim! Esqueci de mencionar esse outro detalhe na mensagem anterior. Todas as funções precisam ter `@importFrom` e `@export`.

**Comment by kguidonimartins** [comment]
Subi a documentação ba05fbda7c0837163cfdaa3e4565d93ac73508d1

**Comment by brunobrr** [comment]
> Sim! Esqueci de mencionar esse outro detalhe na mensagem anterior. Todas as funções precisam ter `@importFrom` e `@export`.

Valeu!!! No importFrm devem ser adicionado o nome do pacote e as funções importadas? Isso mesmo? E no @export? Qual a diferença para o @return?

**Comment by kguidonimartins** [comment]
Isso. No importFrom, primeiro aparece o nome do pacote e depois o nome das
funções usadas daquele pacote. O return você informa o que a função retorna
para o usuário (essencialmente, é o objeto dentro do último return da
função). O export disponibiliza a função para os usuários. Por exemplo,
poderíamos ter funções internas no pacote que não são usadas pelos usuários
e por isso não ficam disponíveis quando usamos `bdc::` mais a tecla Tab.

**Comment by sjevelazco** [comment]
Pessoal temos que melhorar o exemplo da função bdc_filter_out_flags

**Comment by brunobrr** [comment]
@sjevelazco, a função bdc_transposed_coordinates tem um argumento de distância que corrige pontos só até essa distância do país. Dessa forma, pontos além dessa distância não são corrigidos. Essa distância foi utilizada por algum propósito?
