### ISSUE TITLE
Problemas a serem resolvidos no pacote

### ISSUE THREAD

**Issue by brunobrr** [brunobrr/bdc#146]
- [ ] Adicionar uma tabela (ou lista) das funções na página inicial do site **(Bruno)**
- [ ] Criar faq **(Bruno)**
- [ ] Conferir exemplos que não estão rodando: "devtools::run_examples(run_dontrun = TRUE)" **(Lucas)**
- [x] Atualizar o logo
- [ ] Atualizar o site
- [x] Inserir função para criar diretório em todas funções que produzem output. bdc_clean_names, por exemplo
- [x] Remover argumento workflow_step das funções de report e figures

**Comment by kguidonimartins** [comment]
Oi Bruno

Já testei o drake, mas não conheço os outros.  Qual seria o objetivo?

**Comment by brunobrr** [comment]
@kguidonimartins, vi esse pacote em uma aula que estou assistindo e fiquei curioso, rs
