### ISSUE TITLE
Transposed coordinates

### ISSUE THREAD

**Issue by brunobrr** [brunobrr/bdc#149]
@sjevelazco  a função bdc_transposed_coordinates tem um argumento de distância que corrige pontos só até essa distância do país. Dessa forma, pontos além dessa distância não são corrigidos. Essa distância foi utilizada por algum propósito?

**Comment by sjevelazco** [comment]
Olá Bruno adicionei um argumento novo (border_buffer) com um valor default de 0.2. Atualizei o exemplo porque ele não estava rodando. Qualquer coisa me avise.
