### ISSUE TITLE
Remoção de dependências

### ISSUE THREAD

**Issue by kguidonimartins** [brunobrr/bdc#158]
Pessoal, temos uma lista relativamente grande de pacotes como dependência. Precisamos reduzir essa lista ao máximo. 

Por favor, marquem a caixa dos pacotes que vocês acham que são necessários para o funcionamento do nosso pacote. Aqueles que não forem marcados, vamos movê-los para uma lista de sugestão. Isso será informado pela própria função que depende desse pacote não marcado na lista.

  - [x]  here
  - [x]  dplyr
  - [ ]  purrr
  - [ ]  readr
  - [ ]  fs
  - [ ]  rlang
  - [x]  doParallel
  - [x]  foreach
  - [x]  sf
  - [x]  data.table
  - [ ]  flora
  - [ ]  geobr
  - [ ]  lubridate
  - [ ]  plyr
  - [ ]  qs
  - [ ]  rvest
  - [x]  sp
  - [x]  stringr
  - [ ]  vroom
  - [ ]  xml2
  - [x]  CoordinateCleaner
  - [ ]  Hmisc
  - [x]  countrycode
  - [ ]  rangeBuilder
  - [ ]  tidyselect
  - [x]  raster
  - [ ]  rnaturalearth
  - [x]  stringdist
  - [x]  stringi
  - [x]  taxadb
  - [ ]  cowplot
  - [x]  ggplot2
  - [ ]  kableExtra
  - [ ]  knitr
  - [ ]  scales
  - [x]  tibble
  - [ ]  rgnparser
  - [x]  rworldmap
  - [x]  magrittr

**Comment by kguidonimartins** [comment]
Lembrete:

```r
check_require <- function(pkg) {
  full_pkgname <- pkg
  pkgname <- basename(full_pkgname)

  if (!requireNamespace(pkgname, quietly = TRUE)) {
    usethis::ui_stop(
      "Package {usethis::ui_field(pkgname)} needed for this function to work!
       Solution: You can install it with `misc::ipak(\"{ui_field(full_pkgname)}\")`"
    )
  }
}
```

**Comment by sjevelazco** [comment]
Tem três pacotes que são só para leer e salvar dados vroom data.table e readr, acho que deveriamos deixar só um deles

**Comment by brunobrr** [comment]
Concordo com @sjevelazco, acho melhor deixar apenas o data.table e remover os outros.

Minha sugestão. Acho que os seguintes pacotes podem ser removidos pode não estarem sendo utilizados (mas é preciso conferir):
- [ ] flora
- [ ] geobr
- [ ] fs
- [ ] vroom (sugestão Santiago)
- [ ] readr

Acho que os seguintes pacotes são pouco utilizados:
- [ ] kableExtra
- [ ] Hmisc
- [ ] plyr
- [ ] rvest
- [ ] cowplot
- [ ] scales

**Comment by brunobrr** [comment]
@lucas-jardim, alguma sugestão?

**Comment by brunobrr** [comment]
Great work folks :)
