### ISSUE TITLE
bdc_clean_names error 

### ISSUE THREAD

**Issue by paschatz** [brunobrr/bdc#241]
I am trying to run the ```bdc_clean_names()``` function and I get the following error:

```{r}
bdc_clean_names(spatialnetdf$genus_species, save_outputs = FALSE)'
```
```> The latest gnparser version is v1.6.9
Error in utils::download.file(grep(os, urls, value = TRUE), file, mode = "wb") : 
  lengths of 'url' and 'destfile' must match
```

any idea how to resolve? (R version 4.2.2 and bdc 1.1.2)

**Comment by kguidonimartins** [comment]
Thanks for reporting. Are you running this on Windows? If yes, @hazeljanderson suggested in the issue #230 that running `options(download.file.method = "wininet")` before `bdc_clean_names()` could solve your problem. Could you try that first, please?

**Comment by kguidonimartins** [comment]
Hi @paschatz, did you try the solution?

**Comment by paschatz** [comment]
my sincerely apologies for the delayed response. yes, now it works nicely. you can close the issue.

**Comment by kguidonimartins** [comment]
No problem @paschatz! I'm glad to hear that your issue has been resolved. Be sure to report if you have another problem with `bdc`. I'm closing this issue.
