### ISSUE TITLE
some functions create Output dir

### ISSUE THREAD

**Issue by black-snow** [brunobrr/bdc#244]
Apparently, some functions create an (empty) `Output` dir and there's no way to stop them.

`bdc_clean_names` seems fine with `save_outputs = FALSE` but `bdc_query_names_taxadb` seems to create the directories even when the export arg is false.

I didn't look at the code (yet) so I didn't pinpoint it. It would be nice if no method created any files or directories "without permission" (i.e., all of them had a parameter for that with a sensible default off).

Cheers!

**Comment by kguidonimartins** [comment]
Thanks for reporting! Can you test the new development version of `bdc`?

```
if (!require("remotes")) install.packages("remotes")
remotes::install_github("brunobrr/bdc", force = TRUE)
stopifnot(packageVersion("bdc") == "1.1.4")
```

**Comment by black-snow** [comment]
Looks okay, thanks!
