### ISSUE TITLE
doParallel shouldn't be just a suggestion or parallel should default to false

### ISSUE THREAD

**Issue by black-snow** [brunobrr/bdc#250]
I was wondering why I had to load `doParallel` even though I don't use it in my code. The reason is that `bdc_suggest_names_taxadb()` has an argument `parallel`, that defaults to `TRUE` and given that `parallel == TRUE` bdc utilizes `doParallel`: https://github.com/brunobrr/bdc/blob/6932e76d27f2d2a15707739b49e19c897791253b/R/bdc_suggest_names_taxadb.R#L129

I think the default for `parallel` should either be `FALSE` or you should move `doParallel` from suggestions up to imports.

**Comment by kguidonimartins** [comment]
doParallel is required to register/open connections with cores.

**Comment by black-snow** [comment]
> doParallel is required to register/open connections with cores.

Hi @kguidonimartins what *cores* and how does this address the issue that it just fails with its defaults?

**Comment by kguidonimartins** [comment]
Cores on which data processing is distributed.  And about the issue you're
reporting, well there isn't an apparent problem.  The function works as
expected.  Tests report no issues.  Anyway, if you prefer, submit a PR with
your suggestions.  If both checks and tests pass, we accept your changes.

**Comment by black-snow** [comment]
Aight. The easiest fix is to just move it up to the imports: https://github.com/brunobrr/bdc/pull/251
