### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [brunobrr/bdc#253]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

This package is harmed in the scenario for CMD check using sp evolution status 2 (substitute
use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path because of strong dependence on `CoordinateCleaner`. No response yet to issue raised there last year: https://github.com/ropensci/CoordinateCleaner/issues/78. Please help the maintainer of that package to protect your package and workflows.

**Comment by kguidonimartins** [comment]
Thanks, @rsbivand! We appreciate you bringing these issues to our attention, and we'll monitor them closely. Also, we plan to lend a hand to the CoordinateCleaner team during this transition.

**Comment by rsbivand** [comment]
@kguidonimartins Less than three weeks remain to fix this.

**Comment by kguidonimartins** [comment]
Closing this issue.

Ref: https://github.com/ropensci/CoordinateCleaner/issues/78#issuecomment-1764201921
