### ISSUE TITLE
Loop 0 is not valid: Edge 1028 has duplicate vertex with edge 1033

### ISSUE THREAD

**Issue by julianastropp** [brunobrr/bdc#255]
I am trying to run step 5 (Getting country names from valid coordinates) of the Pre-filter and received the following error message:

**Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented = oriented,  :                    
  Loop 0 is not valid: Edge 1028 has duplicate vertex with edge 1033**

Any help is welcome :-)

Thanks!

**Comment by kguidonimartins** [comment]
Sorry about that. We made recent changes, which probably resolves the related problem. Can you reinstall the `bdc`, refresh your session and try again?

```r
if (!require("remotes")) install.packages("remotes")
remotes::install_github("brunobrr/bdc", force = TRUE)
```

**Comment by kguidonimartins** [comment]
I'm closing this issue for now. Feel free to reopen if your problem persists.
