### ISSUE TITLE
erro na função bdc_country_from_coordinates

### ISSUE THREAD

**Issue by jaum20** [brunobrr/bdc#261]
Estou tentando usar a função mas recebo o erro:

```
Error in `dplyr::filter()`:                                                                                                                                                            
ℹ In argument: `!is.na(data_no_country[[lat]])`.
Caused by error in `.subset2()`:
! invalid negative subscript in get1index <real>
```

alguma ideia do que pode ser?

**Comment by kguidonimartins** [comment]
oi @jaum20, estamos atualizando o pacote e pode ser que a versão disponível aqui resolva seu problema. Por favor, reinstale o bdc e tentei novamente. Siga as instruções abaixo:

```r
install.packages("remotes")
remotes::install_github("brunobrr/bdc", force = TRUE)
```

Se o problema persistir, peço que nos forneça uma pequena amostra dos dados para verificarmos, tudo bem?

**Comment by jaum20** [comment]
Agora está funcionando. Obrigado
