### ISSUE TITLE
Issue with bdc_query_names_taxadb

### ISSUE THREAD

**Issue by GilbertAlarcon-Cruz** [brunobrr/bdc#262]
Hello. It's me again. After assembling more data I decided to run bdc_query_names_taxadb() again and now get the following message:

```
It looks like you tried to incorrectly use a table in a schema as source.
ℹ If you want to specify a schema use `in_schema()` or `in_catalog()`.
ℹ If your table actually contains "." in the name use `check_from = FALSE` to silence this message.
```

I tried typing in the suggested commands in the RStudio console but nothing seems to happen. Do you know what I should do about this message?

**Comment by GilbertAlarcon-Cruz** [comment]
It turns out the command still runs without any issues. I am still not sure what the message means.

**Comment by kguidonimartins** [comment]
hi @GilbertAlarcon-Cruz, this message originates from the taxadb package that the bdc depends. Therefore, this message will continue to appear until the taxadb package maintainer solves this issue. I suggest that you update the taxadb (with `devtools::install_github("ropensci/taxadb")`) and try again. The message is expected to change, but this should not affect the results returned by bdc functions. I'm closing this issue for now. Feel free to reopen if necessary.
