### ISSUE TITLE
Warning message ao executar a função "check_pf <-   bdc_coordinates_transposed( )"

### ISSUE THREAD

**Issue by Barros56789** [brunobrr/bdc#263]
**Quando executo** 

check_pf <-
  bdc_coordinates_transposed(
    data = check_pf,
    id = "database_id",
    sci_names = "scientificName",
    lat = "decimalLatitude",
    lon = "decimalLongitude",
    country = "country_suggested",
    countryCode = "countryCode",
    border_buffer = 0.2, 
    save_outputs = FALSE)

 **aparece a seguinte mensagem:** 

Warning message:
Using one column matrices in `filter()` was deprecated in dplyr
1.1.0.
ℹ Please use one dimensional logical vectors instead.
ℹ The deprecated feature was likely used in the bdc package.
  Please report the issue at
  <https://github.com/brunobrr/bdc/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this
warning was generated.

**Comment by brunobrr** [comment]
Olá,

Essa mensagem é resultado de alterações recentes feitas no pacote dplyr, o
qual bdc depende.
Estamos fazendo atualizações no nosso pacote para incorporar as
atualizações no dplyr.

Assim, em breve, essa mensagem não deverá mais aparecer.
Um abraço,
Bruno

**Comment by kguidonimartins** [comment]
@Barros56789 , a mensgem não afeta os resultados. Vou fechar essa issue.
