### ISSUE TITLE
Erro em "00_Merge_Datasets"

### ISSUE THREAD

**Issue by zanderaugusto** [brunobrr/bdc#98]
https://github.com/brunobrr/bdc/blob/0ee5cae41cfe470f6c3203a341dd686922ee8814/R/bdc_standardize_datasets.R#L144

`
Error in is.na.integer64(x) : 
  REAL() can only be applied to a 'numeric', not a 'character'
`

Meu input (variável "metadata"):
https://github.com/zanderaugusto/bdc/blob/master/Config/DatabaseInfo.csv

**Comment by brunobrr** [comment]
Valeu, @kguidonimartins, você pode conferir, por favor?

**Comment by kguidonimartins** [comment]
@zanderaugusto, você poderia compartilhar seus datasets comigo?

**Comment by kguidonimartins** [comment]
Alternativamente, você poderia substituir o trecho do código indicado por:

```r
merged_database <-
    merged_database %>% 
    tidyr::drop_na()
```

**Comment by zanderaugusto** [comment]
> @zanderaugusto, você poderia compartilhar seus datasets comigo?

https://github.com/zanderaugusto/bdc/tree/master/Input_files

**Comment by kguidonimartins** [comment]
Zander, aparentemente o problema está na hora de salvar os 
arquivos individualmente como =.qs=. Tentei modificar no seu 
repositório, mas não encontrei a última versão da função lá. Vou 
modificar aqui no nosso repositório mesmo. Você poderia tentar de 
novo?


--
Karlo

**Comment by kguidonimartins** [comment]
Modificada aqui: https://github.com/brunobrr/bdc/commit/523fa9518f7e332d46f13cc88c366925770fe908
